### ISSUE TITLE
Update the quarterly donations policy (10%)

### ISSUE THREAD

**Issue by karantan** [niteoweb/handbook#109]
## The Story

As a Nitean,
I want to update the quarterly donations policy,
so that it reflects the decision we made on IRL#4.

### Problem/Task

On IRL#4 we've voted on increasing donations from 1% to 10%.

### Proposal

Update the [Profit Sharing policy](https://github.com/niteoweb/handbook/blob/master/profit-sharing.md).

### Pitfalls

/

## Best Practices (DoD)

- Documentation is up-to-date:
  * Handbook pages

## Expectations (AC)

- [x] Updated [Profit Sharing policy on Handbook](https://github.com/niteoweb/handbook/blob/master/profit-sharing.md).
- [x] [User Story Demo](https://github.com/niteoweb/operations/releases/download/sprint_15/109-operations-Update-the-quarterly-donations-policy.mkv) uploaded to [Sprint release](https://github.com/niteoweb/operations/releases/latest).

[Work Process]: https://github.com/niteoweb/handbook/blob/master/work-process.md
[User Story]: https://github.com/niteoweb/handbook/blob/master/issue-user-story.md

**Comment by cas--** [comment]
Ticked `Updated Profit Sharing policy on Handbook.` and uploaded demo

**Comment by dmurko** [comment]
Looks good to me.
