### ISSUE TITLE
Open salaries policy

### ISSUE THREAD

**Issue by karantan** [niteoweb/handbook#110]
## The Story

As a Nitean,
I want to add information about our open salaries policy,
so that it reflects what we've decided on IRL#4.

### Problem/Task

We've decided we'll have an open salaries policy. This means Niteans are able to review each others salaries, profit share and allowance. 

There will be no list for simple comparing (because that is not the point) but manually one-by-one through Scrooge app for anyone who is interested so that they have better information on setting salaries.

### Proposal

Update the [Handbook salary policy](https://github.com/niteoweb/handbook/blob/master/people/salary.md#setting-your-salary) with more information.

### Pitfalls

Open salaries can cause different issues however, we've decided that the benefits outweigh the pitfalls.

## Best Practices (DoD)

- Documentation is up-to-date:
  * Handbook pages

## Expectations (AC)

- [x] Add a section about our Open Salaries policy in the [Salary Handbook docs](https://github.com/niteoweb/handbook/blob/master/people/salary.md#setting-your-salary).
- [x] [User Story Demo](https://github.com/niteoweb/operations/releases/download/sprint_20/handbook-110-open-salaries-policy.mp4) uploaded to [Sprint release](https://github.com/niteoweb/operations/releases/latest).

[Work Process]: https://github.com/niteoweb/handbook/blob/master/work-process.md
[User Story]: https://github.com/niteoweb/handbook/blob/master/issue-user-story.md

**Comment by dmurko** [comment]
SP: 1

**Comment by suzil** [comment]
SP： 1

**Comment by cas--** [comment]
Ticked: `Add a section about our Open Salaries policy in the Salary Handbook docs.`
