### ISSUE TITLE
Change in profit sharing policy

### ISSUE THREAD

**Issue by cas--** [niteoweb/handbook#111]
@dmurko commented on [Sun Jan 07 2018](https://github.com/niteoweb/operations/issues/389)

## The Story

As a Nitean,
I want to update our profit sharing policy,
so that the split is fairer and more motivating to newcomers.

### Problem/Task

With the existing profit sharing policy, we did two things poorly: we motivated overwork due to the points being based on hours worked; we rewarded team members who were longer with Niteo way too much (in practice Dejan and Nejc got more than half of the profit sharing).

### Proposal

We propose to change the current formula to `log(months_at_company)` that will be used to calculate the points and based on those points each Nitean will get % of the total profit.

Hours also count, but only up to expected hours, no overtime counts. Vacation hours also count. We want to incentivize using vacation hours and disincentivize overtime. In other words, you receive less profit share only if you've used any unpaid vacation.

### Pitfalls

/

## Best Practices (DoD)

- Documentation is up-to-date:
  * Handbook pages

## Expectations (AC)

- [x] Updated [Profit Sharing policy](https://github.com/niteoweb/handbook/blob/master/profit-sharing.md).
- [x] [User Story Demo](https://github.com/niteoweb/operations/releases/download/sprint_15/111-handbook-Change-in-profit-sharing-policy.mkv) uploaded to [Sprint release](https://github.com/niteoweb/operations/releases/latest).

[Work Process]: https://github.com/niteoweb/handbook/blob/master/work-process.md
[User Story]: https://github.com/niteoweb/handbook/blob/master/issue-user-story.md

**Comment by cas--** [comment]
@karantan commented on [Sun Jan 07 2018](https://github.com/niteoweb/operations/issues/389#issuecomment-355831398)

> Hours also count, but only up to expected hours, no overtime counts. Vacation hours also count.

I would remove this because it doesn't make sense when you combine it with the rest of the paragraph.

I would just leave this:

`You receive less profit share only if you've used any unpaid vacation.`

And because of this the "advanced" formula is:
`log(months_at_company) * (1 - procentage_of_unpaid_vacation / 100)`


  

---

@karantan commented on [Sun Jan 07 2018](https://github.com/niteoweb/operations/issues/389#issuecomment-355831469)

SP: 1

---

@zupo commented on [Tue Jan 09 2018](https://github.com/niteoweb/operations/issues/389#issuecomment-356103755)

SP: 1

---

@zupo commented on [Tue Jan 09 2018](https://github.com/niteoweb/operations/issues/389#issuecomment-356103847)

Can be moved to Handbook repo?

---

@zupo commented on [Tue Jan 09 2018](https://github.com/niteoweb/operations/issues/389#issuecomment-356339396)

One more thing. This needs a very long commit message, explaining all problems of the old policy and how this new policy addresses them. Profit sharing is a super sensitive subject and I want to have all changes to it well documented.

**Comment by karantan** [comment]
And that is why I don't move issues ^^

**Comment by cas--** [comment]
Ticked `Updated Profit Sharing policy` and demo uploaded.
