### ISSUE TITLE
Using Slack - avoid private discussions

### ISSUE THREAD

**Issue by dmurko** [niteoweb/handbook#112]
## The Story

As a Nitean,
I want my coworkers to avoid private work conversations,
so that I'm not out of the loop on discussions that might interest me.

### Problem/Task

Often times people revert to private discussions between two people. We need to avoid that so that everyone knows what everyone else is doing. 

### Proposal

Write a section in [Using Slack](https://github.com/niteoweb/handbook/blob/master/using-slack.md).

This only applies to work things. People can discuss anything else they'd like on private.

### Pitfalls

We need to keep reminding people of the policy.

## Best Practices (DoD)

- Documentation is up-to-date:
  * Handbook pages

## Expectations (AC)

- [ ] [Using Slack](https://github.com/niteoweb/handbook/blob/master/using-slack.md) has a section about avoiding private work discussions.
 - [ ] [User Story Demo](<demo-url-here>) uploaded to [Sprint release](https://github.com/niteoweb/operations/releases/latest).

[Work Process]: https://github.com/niteoweb/handbook/blob/master/work-process.md
[User Story]: https://github.com/niteoweb/handbook/blob/master/issue-user-story.md

**Comment by karantan** [comment]
I don't think that writing a paragraph in the handbook will change this. We have stated this multiple times and if this is still going on we need to change our approach.

@zupo any ideas?

**Comment by suzil** [comment]
Maybe one of those periodic tips that appear in Slack should be dedicated to this?

**Comment by cas--** [comment]
Sometimes a private discussion is good to avoid noise/distraction in the channels. Say where you one person's opinion before taking it to the group. So I'm not sure that private discussions are a bad thing...

**Comment by zupo** [comment]
Sometimes, yes, but not very often. 

The only way to manage this (as any other thing) is to measure it. We can make it a goal to have less than a certain % of slack messages private. Slack send me an email weekly with this number. Currently, it is `Of those, 34% were in public channels, 2% were in private channels, and 65% were direct messages.` We used to have 60% public and the number has been going down steadily during the recent months.

I'm +1 for adding a Handbook entry.

**Comment by dmurko** [comment]
SP: 1

**Comment by cas--** [comment]
SP: 1

**Comment by cas--** [comment]
@dmurko A nitpick but this is an operations issue, not a handbook issue.

**Comment by zupo** [comment]
Uhm no? It's a change to our process that is described in the Handbook. 

Generally, if a story concerns only one repo, it should be in that repo.
