### ISSUE TITLE
Repository support guidelines link

### ISSUE THREAD

**Issue by dmurko** [niteoweb/handbook#114]
<img width="600" alt="screen shot 2018-01-10 at 14 12 44" src="https://user-images.githubusercontent.com/1309671/34775008-e7f68028-f611-11e7-910d-f21bfa73b034.png">

This links to https://github.com/niteoweb/handbook/blob/master/support.md but that is customer support docs that has nothing to do with the Handbook.

**Comment by cas--** [comment]
This was fixed by the move of `support.md` to `roles` folder.
