### ISSUE TITLE
Fun reading list for onboarding

### ISSUE THREAD

**Issue by dmurko** [niteoweb/handbook#116]
You will not fit in if you don't know about this. :P

- [South Park - Underpants Business plan](https://www.youtube.com/watch?v=tO5sxLapAts)
- [xkcd comics](https://xkcd.com/)
- [The Oatmeal](http://theoatmeal.com/), especially [How a Web Design Goes Straight To Hell](http://theoatmeal.com/comics/design_hell) to remind ourselves about the nightmares of working with clients and why we went the SaaS route

**Comment by karantan** [comment]
😱 
...
😄

**Comment by dmurko** [comment]
Added to https://github.com/niteoweb/operations/blob/master/.github/ISSUE_TEMPLATES/onboarding-trialist-2-welcome.md
