### ISSUE TITLE
Documentation for interviewing and hiring

### ISSUE THREAD

**Issue by marbeann** [niteoweb/handbook#118]
## The Story

As a PeopleOps,
I want a structured interview and hiring process,
so that I don't miss anything vital and everything will go smoothly.

### Problem/Task

Our documentation for the hiring and interviewing process needs to be heavily updated: https://intra.niteoweb.com/people-operations/job-posting-and-interviews

Things needed to be added/consolidated:

- Workable (for job posting and managing applications).
- Hiring committee (decided organically, those who want to be part of the hiring process and has something to offer)
- Set job posting, pre-interview, and interview questions for each department (development, marketing, support, designers).

  - CBO posting: https://github.com/niteoweb/operations/issues/237
  - https://intra.niteoweb.com/people-operations/interviewing-marketing-staff
  - https://niteo.workable.com/jobs/463716/preview?show_description=true)
  - https://niteo.workable.com/jobs/587702/preview?show_description=true
  - Marbe's notes for pre-interview.

- Instructions once hired ie Trialist status and salary policy.

### Proposal

Update and consolidate everything in our Handbook.

### Pitfalls

Long document and can get messy.

## Best Practices (DoD)

- Documentation is up-to-date:
  * Handbook pages
  * Intra docs or reports

## Expectations (AC)

- [ ] Handbook includes documentation for interviewing and hiring.
- [ ] Intra documents for interviewing and job posting are archived.
- [ ] [User Story Demo](<demo-url-here>) uploaded to [Sprint release](https://github.com/niteoweb/operations/releases/latest).

[Work Process]: https://github.com/niteoweb/handbook/blob/master/work-process.md
[User Story]: https://github.com/niteoweb/handbook/blob/master/issue-user-story.md

**Comment by karantan** [comment]
SP: 2 - multiple Niteans will be involved. Right?

**Comment by marbeann** [comment]
SP: 2

And yes, multiple.

**Comment by dmurko** [comment]
SP: 5

**Comment by cas--** [comment]
SP: 3

**Comment by dmurko** [comment]
I wrote this for https://github.com/niteoweb/operations/issues/407.

## Process

They need to do the whole test in one sitting and record everything.

- Job posting
- Vervoe: Basic questions (to filter out timewasters)
- Vervoe: Advanced questions (to find people knowledgeable with WordPress)
- Interview on Skype, chat, and audio to get a feel for them, have them ask questions and get all other information needed.

### Job Posting

- [info about the job]
- [info about the project]
- [what we expect]
- [what we offer]
- [how to apply, request one sitting/recording]

### Basic Questions

- [start recording]
- [qualifiable question] - what is our hosting project
- [location, preferred time for work]
- [latest job experience in support in 200 words]
- [their skill set, what do they enjoy, what they don't like doing etc.]
- [changing nameservers on registrar]
- [upload recording]

### Advanced Questions

- [start recording]
- [common issues customers encountered in your previous work with WordPress]
- [wordpress questions]
- [changing hosts file]
- [directing domain to IP on registrar]
- [upload recording]

**Comment by dmurko** [comment]
This is now implemented in our checklists and  as part of the Workable process.
