### ISSUE TITLE
Arrange the handbook pages into sub-folders

### ISSUE THREAD

**Issue by cas--** [niteoweb/handbook#124]
## The Story

As an Nitean,
I want the handbook to be easier to navigate,
so that I can quickly look up company information.

### Problem/Task

The handbook is a flat-file structure so there is no grouping of similar topics making file-browser navigation harder.  

### Proposal

 * Arrange the handbook pages into subfolders
 * Update the index.md and other pages to point to new locations.
 * Update templates to point to new locations. 

### Pitfalls

Break handbook links from places not considered

## Best Practices (DoD)

- Documentation is up-to-date:
  * Handbook pages
  * Intra docs or reports
  * Sphinx technical docs

## Expectations (AC)

 - [x] The handbook pages are organised into folders.
 - [x] Links to the handbook pages in templates are correct
 - [x] [User Story Demo](https://github.com/niteoweb/operations/releases/download/sprint_16/handbook-124-Arrange-handbook-into-sub-folders.mp4) uploaded to [Sprint release](https://github.com/niteoweb/operations/releases/latest).

[Work Process]: https://github.com/niteoweb/handbook/blob/master/work-process.md
[User Story]: https://github.com/niteoweb/handbook/blob/master/issue-user-story.md

**Comment by cas--** [comment]
SP: 1

**Comment by zupo** [comment]
SP: 1

**Comment by dmurko** [comment]
SP: 1 as long as it doesn't expand into other fixes.

**Comment by suzil** [comment]
SP: 1

**Comment by marbeann** [comment]
SP: 1

**Comment by cas--** [comment]
Ticked:
* `The handbook pages are organised into folders.`
* `Links to the handbook pages in templates are correct`
* `User Story Demo uploaded to Sprint release.`
