### ISSUE TITLE
Handbook writing guidelines 

### ISSUE THREAD

**Issue by cas--** [niteoweb/handbook#125]
## The Story

As a Nitean,
I want guidelines on writing documentation in the Handbook,
so that documentation is consistent and readable.

### Problem/Task

From discussions at IRL4, it was decided to improve the Handbook: https://github.com/niteoweb/operations/issues/380#issuecomment-355834679

### Proposal

The following are guidelines are to be included:

* Gender neutral language.
* Aim to use [Simplified English](https://simple.wikipedia.org/wiki/Simplified_English) not just [plain English](https://www.techscribe.co.uk/techw/plain-english-problems.htm). I propose using this reference document: [ASD-STE100-ISSUE-7.pdf](https://github.com/niteoweb/handbook/files/1964422/ASD-STE100-ISSUE-7.pdf)
 
* Spelling and grammar is in American English.
* Add table of contents to pages to help navigation.
* Page length (under 200 lines) if longer consider splitting into separate sections.
* List should be sentence case as per [wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Lists#Bulleted_lists)
* Headings should be sentence case. [Sentence vs title case](https://www.snappysentences.com/sentence-case-v-title-case/)
* Any reference urls should be placed in the footer of the document to keep the raw text easy to edit.
* In order to standardise the letter case of terminology, it should be normal sentence case. Unless a recognized mark e.g. 'Scrum' and 'scrum master' but not 'Scrum master'.

Reference: 
 * [gitlab handbook](https://gitlab.com/gitlab-com/www-gitlab-com/tree/master/source/handbook)
 * [basecamp handbook](https://github.com/basecamp/handbook)

## Best Practices (DoD)

- Documentation is up-to-date:
  * Handbook pages

## Expectations (AC)

 - [ ] [User Story Demo](https://github.com/niteoweb/operations/releases/download/sprint_26/handbook-125-add-writing-guide.mp4) uploaded to [Sprint release](https://github.com/niteoweb/operations/releases/latest).

[Work Process]: https://github.com/niteoweb/handbook/blob/master/work-process.md
[User Story]: https://github.com/niteoweb/handbook/blob/master/issue-user-story.md

**Comment by suzil** [comment]
This is a nice guide: https://www.plainlanguage.gov/

**Comment by cas--** [comment]
[Using the correct terms – Shall, Will, Should](http://reqexperts.com/blog/2012/10/using-the-correct-terms-shall-will-should/)

**Comment by cas--** [comment]
A few reference notes on letter case:
  * Use `Sentence case` for all headings. 
  * In order to standardise the terminology letter case it should be normal sentence case. Unless a recognized mark e.g. Scrum but scrum master. 

These are based on the wikipedia encyclopedic standards and although not perfect, gives an accessible reference point. e.g. https://en.wikipedia.org/wiki/Scrum_(software_development)

**Comment by dmurko** [comment]
Why not capitized headings? I prefer those for headings.

**Comment by suzil** [comment]
@cas-- I think using the word "shall" sounds kind of pretentious? It's not even that clear to me since it's almost never used. plaintext.gov wrote an [article that "shall" should be replaced with "must"](https://www.plainlanguage.gov/guidelines/conversational/use-must-to-indicate-requirements/).

**Comment by zupo** [comment]
After lots of thought I think we should:
* adopt Wikipedia page
* make our style guide as simple/small as possible, basically just reference Wikipedia styles
* do it today/now so we can start applying it

Need +1 from @dmurko who was not on zoom for the discussion.

**Comment by dmurko** [comment]
+1
