### ISSUE TITLE
Move from Sick Hours to Sick Days

### ISSUE THREAD

**Issue by zupo** [niteoweb/handbook#139]
## The Story

As a Nitean,
I want to simplify the Sick Leave policy,
so that I can better understand how to use it and then actually do use it.

### Problem/Task

I get asked all the time how to properly track Sick Hours. Apparently, something is wrong with the policy, it's too complicated.

### Proposal

Move from Sick Hours to Sick Days. If you need to take two hours off, just do it, we have plenty of vacation hours, unpaid vacations, etc.

But if you need to take more than a few hours to get well, then just take the entire day to get good rest. Better to be safe than sorry.

### Pitfalls

* Scrooge needs to be updated, but shouldn't be a problem.

## Best Practices (DoD)

- Documentation is up-to-date:
  * Help Center articles
  * Handbook pages
  * Intra docs or reports
  * Sphinx technical docs
- Product users are informed (e.g. major feature Blog post)
- Test coverage is 100%.

## Expectations (AC)

- [x] Sick Leave policy in Handbook has been updated to reflect the move from tracking sick hours to sick days.
- [x] Scrooge has been updated to support adding Sick Days to Niteans' data.yaml file.
- [x] [User Story Demo](https://github.com/niteoweb/operations/releases/download/sprint_22/handbook-139-sick-days.mp4) uploaded to [Sprint release](https://github.com/niteoweb/operations/releases/latest).

[Work Process]: https://github.com/niteoweb/handbook/blob/master/work-process/work-process.md
[User Story]: https://github.com/niteoweb/handbook/blob/master/work-process/user-stories.md

**Comment by dmurko** [comment]
Quick note: a sick day is 80% of a regular day, so 6 hours.

**Comment by suzil** [comment]
SP： 1

**Comment by zupo** [comment]
Ticked `Sick Leave policy in Handbook has been updated to reflect the move from tracking sick hours to sick days` and `Scrooge has been updated to support adding Sick Days to Niteans' data.yaml file`.

**Comment by zupo** [comment]
Demo uploaded.
