### ISSUE TITLE
Handbook URLs checker

### ISSUE THREAD

**Issue by ImaduddinAMajid** [niteoweb/handbook#194]
## The Story
> *Handbook documents: [User story] & [Work process]*

As a Nitean,
I want to check every URL in Niteo Handbook, 
so that everyone can avoid accessing broken URL when reading the Handbook.

### Problem

There are several broken URL in our Handbook, e.g. [onboarding process] in this [page].

![image.png](https://images.zenhubusercontent.com/5b4e17c13a0eca43415a4009/1816f07b-c9d2-4bbd-9824-4736c931fb18)

Therefore, we need a system to find all URLs in Handbook and check the status of every URL, whether return response `200` **live** or `404` **down**.

### Proposal
Add URLs checker step in local and Travis build so every PR will have its URL fixed when containing any broken URL.

### Pitfalls
The URLs checker could not find the broken URLs.

### Best practices (DoD)
- Documentation is revised:
    e.g. help articles, handbook pages, Intra reports or technical docs.
- Product users are informed. e.g. blog post describing a new major feature.
- Test coverage is 100%.

### Expectations (AC)
- [x] The handbook has URLs checker
- [x] The handbook URLs checker is run locally
- [x] The handbook URLs checker is run on travis
- [x] [User story demo](https://github.com/niteoweb/operations/releases/download/sprint_31/handbook-194-add-urls-checker.avi) uploaded to [sprint release].

[Work Process]: https://github.com/niteoweb/handbook/blob/master/work-process/work-process.md
[User Story]: https://github.com/niteoweb/handbook/blob/master/work-process/user-stories.md
[Sprint release]: https://github.com/niteoweb/operations/releases/latest
[Onboarding process]: https://github.com/niteoweb/handbook/blob/master/roles/onboarding.md
[Page]: https://github.com/niteoweb/handbook/blob/master/5_People/hiring.md

**Comment by karantan** [comment]
> Add URLs checker step in Travis build so every PR will have its URL fixed when containing any broken URL.

We also need to be able to run it locally so that we see which links are broken.
Add this to proposal and AC.

Other than that it is good.

**Comment by karantan** [comment]
<details><summary>Story estimate</summary>SP: 2</details>

**Comment by by-cx** [comment]
<details><summary>Story estimate</summary>SP: 2</details>

**Comment by karantan** [comment]
@ImaduddinAMajid PR is not merged so you cannot ticked any of the AC items.

**Comment by ImaduddinAMajid** [comment]
OK Karantan.
