### ISSUE TITLE
Move from TravisCI to CircleCI

### ISSUE THREAD

**Issue by zupo** [niteoweb/handbook#252]
## The Story
> *Handbook documents: [User story](https://github.com/niteoweb/handbook/blob/master/2_Operations/user-stories.md) & [Work process](https://github.com/niteoweb/handbook/blob/master/2_Operations/work-process.md)*

As a Nitean,
I want my pull requests to pass/fail faster,
so that I can be more productive.

## Problem

We currently use Travis CI to run tests. In https://github.com/niteoweb/pyramid-realworld-example-app/issues/37 we found that CircleCI takes much less overall time to run all the test cases.

## Proposal

Switch over to CircleCI.

## Pitfalls

Don't see any.

## Best practices (DoD)
- Documentation is revised:
    e.g. help articles, handbook pages or technical docs.
- Product users are informed. e.g. blog post describing a new major feature.
- Test coverage is 100%.

## Expectations (AC)

- [x] We have replaced TravisCI with CircleCI
- [x] [User story demo](https://github.com/niteoweb/operations/releases/download/niteo_62/handbook-252-travisci-to-circleci.mp4) uploaded to [sprint release](https://github.com/niteoweb/operations/releases/latest).

**Comment by suryasr007** [comment]
This can be helpful:
https://circleci.com/docs/2.0/migrating-from-travis/#section=getting-started

**Comment by suryasr007** [comment]
@zupo @karantan 
The Travis CI is failing for two files.
              ./2_Operations/user-stories.md: Issues
              ./2_Operations/work-process.md: Issues
https://travis-ci.com/niteoweb/handbook

After configuring the Circle CI, Even this is failing for the same files.
https://circleci.com/gh/niteoweb/handbook/6

Are these known failures? Am I missing something?

**Comment by zupo** [comment]
What are the errors? Can you fix them?

**Comment by suryasr007** [comment]
The following links are returning 404 in both Travis and Circle CI
https://github.com/settings/replies 
https://github.com/notifications

**Comment by suryasr007** [comment]
As I can see, All the GitHub links are whitelisted, We can append the above entries as well to the whitelist.
